version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\cellogram
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Debug
install:
build:
  parallel: true
build_script:
  - cd c:\projects\cellogram
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%config% -G "Visual Studio 15 2017 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%config% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% Cellogram.sln

#test_script:
 # - ctest -C %config% --verbose --output-on-failure -j 2
