trigger:
- master

jobs:
jobs:
- job: Main
  timeoutInMinutes: 0

  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
  - task: GitHubRelease@1
    inputs:
      gitHubConnection: 'teseoch'
      repositoryName: 'cellogram/cellogram'
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: 'gitTag'
      releaseNotesSource: 'inline'
      releaseNotesInline: 'bla'
      addChangeLog: false

# - job: Main
#   timeoutInMinutes: 0
#   strategy:
#     matrix:
#       windows:
#         imageName: 'vs2017-win2016'

#   pool:
#     vmImage: $(imageName)

#   steps:
#   - task: CMake@1
#     inputs:
#       cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" ..'

#   - task: VSBuild@1
#     inputs:
#       solution: 'build/Cellogram.sln'
#       vsVersion: '15.0'
#       platform: 'x64'
#       maximumCpuCount: true
#       msbuildArchitecture: 'x64'

#   - task: GitHubRelease@1
#     inputs:
#       gitHubConnection: 'teseoch'
#       repositoryName: 'cellogram/cellogram.github.io'
#       action: 'create'
#       target: '$(Build.SourceVersion)'
#       tagSource: 'gitTag'
#       assets: '$(Build.ArtifactStagingDirectory)/*.exe'
#       addChangeLog: false