trigger:
- master

jobs:
- job: Main
  timeoutInMinutes: 0
  strategy:
    matrix:
      windows:
        imageName: 'vs2017-win2016'

  pool:
    vmImage: $(imageName)

  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64" ..'

  - task: VSBuild@1
    inputs:
      solution: 'build/Cellogram.sln'
      vsVersion: '15.0'
      platform: 'x64'
      maximumCpuCount: true
      msbuildArchitecture: 'x64'