%% batch cellogram

% This script is an example on how to run cellogram in batch mode.
% Change the paths below:

% Path to the cellogram executable:
cellogram = 'C:\Users\letobias\Documents\cellogram\build\Release\cellogram.exe'; 

% Path to a json file containing convenient settings (can be generated by running cellogram manually):
settings_file = 'C:\Users\letobias\Google Drive\Cell Cycle\Currently Analyzing\Small\Experiment-54-Image Export-01_s01t02c3\all.json';

% Path to where the files are located:
analysis_files = 'C:\Users\letobias\Google Drive\Cell Cycle\Currently Analyzing\Small';

% Key word which must be contained in the filename:
image_name_must_contain = 'Experiment';

temp = dir(analysis_files);
files = temp(~([temp.isdir]));

%
for k = 2:numel(files)
    N = files(k).name;
    disp(N)
    R = regexp(N,image_name_must_contain);
    if ~isempty(R)
        filename = fullfile(analysis_files,N);
        system(sprintf('%s -i "%s" -s "%s" -c',cellogram,filename,settings_file))
    end
end
